In [9]:
import numpy as np
import pickle
import pandas as pd

In [55]:

np.random.seed(13)

df = pd.read_pickle('../emit_data')



wv = np.random.rand(10000) * 5
elev = np.random.rand(10000) * 6
sza = np.random.rand(10000) * 60


bins = 11
# building intervals
wv_range = np.linspace(np.min(wv),np.max(wv), bins)
e_range = np.linspace(np.min(e),np.max(e), bins)
sza_range = np.linspace(np.min(sza),np.max(sza), bins)


samples_per_space = 1
print(f'num samples to build: {(bins-1)**3*samples_per_space}')

sample_set = []
for _w in range(len(wv_range) - 1):
    for _e in range(len(e_range) - 1):
        for _sza in range(len(sza_range) - 1):
            subset = (wv > wv_range[_w]) & (wv <= wv_range[_w + 1]) & (e > e_range[_e]) & (e <= e_range[_e + 1]) & (sza > sza_range[_sza]) & (sza <= sza_range[_sza + 1])
            perm = np.random.permutation(np.sum(subset))

            samples = np.where(subset)[0][perm[:samples_per_space]]
            sample_set.extend(samples.tolist())

num samples to build: 1000


In [57]:
type(sample_set)

list

In [50]:
wv = np.arange(10)
indices = (wv > 6)

In [51]:
indices

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [52]:
np.sum(indices)

3

In [53]:
p = np.random.permutation(np.sum(indices))
p

array([1, 2, 0])

In [54]:
samp = np.where(indices)[0][p[:1]]
samp

array([8], dtype=int64)

In [14]:

np.random.seed(13)

df = pd.read_pickle('../emit_data')

wv = np.random.rand(10000) * 5
elev = np.random.rand(10000) * 6
sza = np.random.rand(10000) * 60


bins = 10
# building intervals
wv_range = np.linspace(np.min(wv),np.max(wv), bins)
e_range = np.linspace(np.min(e),np.max(e), bins)
sza_range = np.linspace(np.min(sza),np.max(sza), bins)


samples_per_space = 1
print(f'num samples to build: {(bins-1)**3*samples_per_space}')

sample_set = []
for _w in range(2):
    for _e in range(2):
        for _sza in range(2):
            subset = (wv > wv_range[_w]) & (wv <= wv_range[_w + 1]) & (e > e_range[_e]) & (e <= e_range[_e + 1]) & (sza > sza_range[_sza]) & (sza <= sza_range[_sza + 1])
            print('subset: ', len(subset))
            perm = np.random.permutation(np.sum(subset))
            print('perm:', perm)

            samples = np.where(subset)[0][perm[:samples_per_space]]
            print('samples: ', samples)
            sample_set.extend(samples.tolist())
            print('sample_set: ', sample_set)

num samples to build: 729
subset:  10000
perm: [12 19 13 23  3  5  4 22 17 16  9  7 18 10  6 11 14 15 21  8  2  1  0 20]
samples:  [5649]
sample_set:  [5649]
subset:  10000
perm: [11  6  1  0 14  4  9  3  8  2 15 10 16  7 12  5 13]
samples:  [5970]
sample_set:  [5649, 5970]
subset:  10000
perm: [ 6  0  3  2  7  8  1  9  5 10  4]
samples:  [6862]
sample_set:  [5649, 5970, 6862]
subset:  10000
perm: [ 2 11  4  1 15 13  5 10 12  0  9  3  8  6  7 16 14]
samples:  [2060]
sample_set:  [5649, 5970, 6862, 2060]
subset:  10000
perm: [12  8  3 11 15  4  0 10  9  2 14  7 13  1  6  5]
samples:  [7579]
sample_set:  [5649, 5970, 6862, 2060, 7579]
subset:  10000
perm: [ 0  4  3 10 13 14 12 18 17  6 16  9  2  1  8  5  7 15 11 19]
samples:  [371]
sample_set:  [5649, 5970, 6862, 2060, 7579, 371]
subset:  10000
perm: [4 3 6 1 2 5 0 7]
samples:  [6596]
sample_set:  [5649, 5970, 6862, 2060, 7579, 371, 6596]
subset:  10000
perm: [ 8  2 12  6 14  7 10  3  4  9 11 13  1  0  5]
samples:  [4502]
sample_set:  [5

In [66]:
np.random.seed(13)
    
wv = df['wv range']
sza = df['zen']
    
bins = 40
# building intervals
wv_range = np.linspace(np.min(wv),np.max(wv), bins)
sza_range = np.linspace(np.min(sza),np.max(sza), bins)
    
    
samples_per_space = 1
print(f'num samples to build: {(bins-1)**2*samples_per_space}')
    
sample_set = []
for _w in range(len(wv_range) - 1):
    for _sza in range(len(sza_range) - 1):
        subset = (wv > wv_range[_w]) & (wv <= wv_range[_w + 1]) & \
        (sza > sza_range[_sza]) & (sza <= sza_range[_sza + 1])
        perm = np.random.permutation(np.sum(subset))
    
        samples = np.where(subset)[0][perm[:samples_per_space]]
        sample_set.extend(samples.tolist())

num samples to build: 1521


In [67]:
len(sample_set)

1232