In [1]:
import numpy as np
import pandas as pd
import pickle
from idaes import *
#from smt.sampling_methods import LHS
#from idaes.surrogate.pysmo.sampling import HammersleySampling

#from idaes.surrogate.pysmo.sampling import LatinHypercubeSampling

from idaes.core.surrogate.pysmo.sampling import LatinHypercubeSampling

expression symbols from pyomo.core.expr  (deprecated in 6.6.2.dev0) (called
from <frozen importlib._bootstrap>:228)


In [2]:
df = pd.read_pickle('../emit_data')
print(df.shape)
data = df.iloc[:,1:6].copy()
print(type(data))
print(data.columns.values)

(33820, 8)
<class 'pandas.core.frame.DataFrame'>
['elev med' 'zen' 'slope' 'wv range' 'wv med']


In [3]:
data.head()

elev med    zen  slope  wv range  wv med
0      3.17  49.77   9.00      2.69    0.24
1      2.75  49.24   3.77      0.16    0.09
2      2.52  48.71   4.14      0.30    0.12
3      2.55  48.19   1.84      4.10    0.08
4      0.96  47.68   2.41      4.99    3.88

In [10]:
lhs = LatinHypercubeSampling(data, 1500, sampling_type="selection", xlabels = ['elev med', 'zen', 'slope', 'wv range', 'wv med'])

Sampling type:  selection 



In [11]:
samples = lhs.sample_points()


Number of unique samples returned by sampling algorithm: 764


c:\users\vpatro\desktop\idaes-pse\idaes\core\surrogate\pysmo\sampling.py:183: UserWarning: The returned number of samples is less than the requested number due to repetitions during nearest neighbour selection.
  warnings.warn(


In [12]:
samples.shape

(764, 5)

xlabels = ['elev med', 'zen', 'slope', 'wv range', 'wv med']

set_of_labels = xlabels
x_data = data.filter(xlabels).values
print('x data: ', x_data.shape)
data_headers = set_of_labels
print('data headers: ', data_headers)
data_headers_xvars = xlabels
print('data headers xvars: ', data_headers_xvars)
data = data.filter(set_of_labels).values
print('data: ', data.shape)

no_y_vars = x_data.shape[1] - data.shape[1]
print(no_y_vars)
data[:, :no_y_vars]
dist = data[:, :no_y_vars] - data[0]

dist = data - data[0]
l2_norm = np.sqrt(np.sum((dist**2), axis=1))
l2_norm = l2_norm.reshape(l2_norm.shape[0], 1)
distances = np.append(data, l2_norm, 1)
sorted_distances = distances[distances[:, -1].argsort()]
closest_point = sorted_distances[0, :-1]
print(closest_point)

In [87]:
data[0]

array([ 3.17, 49.77,  9.  ,  2.69,  0.24])

In [83]:
dist

array([[  0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [ -0.42,  -0.53,  -5.23,  -2.53,  -0.15],
       [ -0.65,  -1.06,  -4.86,  -2.39,  -0.12],
       ...,
       [ -3.17,  -9.3 ,  -7.01,  -0.94,   2.23],
       [ -2.44, -14.87,  -0.75,   3.26,   2.46],
       [ -2.34, -14.31,  -6.76,   3.21,   1.7 ]])

In [11]:
import lhs

In [91]:
data[:,:-1]

array([[ 3.17, 49.77,  9.  ,  2.69],
       [ 2.75, 49.24,  3.77,  0.16],
       [ 2.52, 48.71,  4.14,  0.3 ],
       ...,
       [ 0.  , 40.47,  1.99,  1.75],
       [ 0.73, 34.9 ,  8.25,  5.95],
       [ 0.83, 35.46,  2.24,  5.9 ]])

In [13]:
lhs_sampler = lhs.LHS(data, 1000, sampling_type="selection", xlabels = ['elev med', 'zen', 'slope', 'wv range', 'wv med'])

AttributeError: 'LHS' object has no attribute 'sampling_type'

In [10]:
samples = lhs.sample_points()

ValueError: operands could not be broadcast together with shapes (33820,0) (5,) 